services :
  app :
    build : .
    volumes :
      - .:/app

    ports :
      - "8000:8000"

    env_file:
      - .env

    image : airesumeparser

    container_name : Resumeparser

    environment :
      - PYTHONUNBUFFERED=1
      - PYTHONPATH= /app

    